//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBLiveVideoEntities : DbContext
    {
        public DBLiveVideoEntities()
            : base("name=DBLiveVideoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mpds_log> mpds_log { get; set; }
        public virtual DbSet<mpds_menu> mpds_menu { get; set; }
        public virtual DbSet<mpds_role> mpds_role { get; set; }
        public virtual DbSet<mpds_role_value> mpds_role_value { get; set; }
        public virtual DbSet<tbApiToken> tbApiTokens { get; set; }
        public virtual DbSet<tbAppLog> tbAppLogs { get; set; }
        public virtual DbSet<tbAppVersion> tbAppVersions { get; set; }
        public virtual DbSet<tbCaseCollection> tbCaseCollections { get; set; }
        public virtual DbSet<tbCaseDeployDev> tbCaseDeployDevs { get; set; }
        public virtual DbSet<tbCaseDeploy> tbCaseDeploys { get; set; }
        public virtual DbSet<tbCaseGoing> tbCaseGoings { get; set; }
        public virtual DbSet<tbCaseLivingShow> tbCaseLivingShows { get; set; }
        public virtual DbSet<tbCaseMessage> tbCaseMessages { get; set; }
        public virtual DbSet<tbCaseMission> tbCaseMissions { get; set; }
        public virtual DbSet<tbCaseMissionDistribution> tbCaseMissionDistributions { get; set; }
        public virtual DbSet<tbCas> tbCases { get; set; }
        public virtual DbSet<tbDepartment> tbDepartments { get; set; }
        public virtual DbSet<tbDeviceIMData> tbDeviceIMDatas { get; set; }
        public virtual DbSet<tbDevice> tbDevices { get; set; }
        public virtual DbSet<tbDiscussionGroupMenber> tbDiscussionGroupMenbers { get; set; }
        public virtual DbSet<tbDiscussionGroup> tbDiscussionGroups { get; set; }
        public virtual DbSet<tbFileDetail> tbFileDetails { get; set; }
        public virtual DbSet<tbRole> tbRoles { get; set; }
        public virtual DbSet<tbUnit> tbUnits { get; set; }
        public virtual DbSet<tbUserIMData> tbUserIMDatas { get; set; }
        public virtual DbSet<mpds_group_user> mpds_group_user { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
        public virtual DbSet<mpds_audio_detail> mpds_audio_detail { get; set; }
        public virtual DbSet<tbCaseGp> tbCaseGps { get; set; }
    }
}
