//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mpds_group_user
    {
        public long id { get; set; }
        public string groupid { get; set; }
        public string type { get; set; }
        public string account { get; set; }
        public string name { get; set; }
        public string dept { get; set; }
        public string deptid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string groupName { get; set; }
        public string isdefault { get; set; }
    }
}
