//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mpds_audio_detail
    {
        public long id { get; set; }
        public string conference_uuid { get; set; }
        public string conference_name { get; set; }
        public string event_name { get; set; }
        public Nullable<System.DateTime> event_time { get; set; }
        public string startor { get; set; }
        public string listener { get; set; }
        public string content { get; set; }
    }
}
