//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAppVersion
    {
        public long ID { get; set; }
        public Nullable<int> isDel { get; set; }
        public byte[] recSN { get; set; }
        public string appType { get; set; }
        public Nullable<int> appVersionNo { get; set; }
        public string appVersionName { get; set; }
        public Nullable<System.DateTime> appPublishTime { get; set; }
        public string appFeatures { get; set; }
        public string appTitle { get; set; }
        public string appDownloadUrl { get; set; }
        public string createuser { get; set; }
    }
}
