//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAppLog
    {
        public string ID { get; set; }
        public Nullable<bool> isDel { get; set; }
        public byte[] recSN { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public string fCode { get; set; }
        public string appVersionCode { get; set; }
        public string appApiUrl { get; set; }
        public string appType { get; set; }
    }
}
