//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCaseMessage
    {
        public Nullable<bool> isDel { get; set; }
        public byte[] recSN { get; set; }
        public string csCode { get; set; }
        public string msgType { get; set; }
        public string msgAbstract { get; set; }
        public string msgFile { get; set; }
        public string uCode { get; set; }
        public Nullable<System.DateTime> msgTime { get; set; }
        public long ID { get; set; }
        public string uLatitude { get; set; }
        public string uLongitude { get; set; }
        public string uPositionName { get; set; }
        public string msgFromType { get; set; }
        public string msgToCode { get; set; }
    }
}
