//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCaseGoing
    {
        public Nullable<bool> isDel { get; set; }
        public byte[] recSN { get; set; }
        public string csCode { get; set; }
        public string cgType { get; set; }
        public string cgAbstract { get; set; }
        public string uCode { get; set; }
        public Nullable<System.DateTime> cgCreateTime { get; set; }
        public string ID { get; set; }
        public string PositionRemark { get; set; }
        public Nullable<decimal> PositionLongitude { get; set; }
        public Nullable<decimal> PositionLatitude { get; set; }
        public string PositionName { get; set; }
        public string uUnitCode { get; set; }
    }
}
