//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCaseLivingShow
    {
        public string ID { get; set; }
        public string caseCode { get; set; }
        public string rtmpUrl { get; set; }
        public string userCode { get; set; }
        public Nullable<bool> livingState { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<bool> isDel { get; set; }
        public byte[] recSN { get; set; }
        public string sourceType { get; set; }
        public string deviceCode { get; set; }
        public Nullable<int> Cumulative { get; set; }
        public string fFirstFrame { get; set; }
    }
}
