//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCaseMission
    {
        public string ID { get; set; }
        public string caseCode { get; set; }
        public Nullable<bool> isDel { get; set; }
        public byte[] recSN { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public Nullable<int> missionStatus { get; set; }
        public Nullable<int> missionLimiTime { get; set; }
        public string toPositionName { get; set; }
        public Nullable<decimal> toPositionLatitude { get; set; }
        public Nullable<decimal> toPositionLongitude { get; set; }
        public string missionRemark { get; set; }
        public Nullable<decimal> routeDistance { get; set; }
        public string createdUserCode { get; set; }
        public string createdPositionName { get; set; }
        public Nullable<decimal> createdPositionLatitude { get; set; }
        public Nullable<decimal> createdPositionLongitude { get; set; }
        public string missionType { get; set; }
        public Nullable<System.DateTime> finishTime { get; set; }
    }
}
