//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCas
    {
        public Nullable<bool> isDel { get; set; }
        public byte[] recSN { get; set; }
        public string csCode { get; set; }
        public string csName { get; set; }
        public string csType { get; set; }
        public string csAddress { get; set; }
        public Nullable<System.DateTime> csTime { get; set; }
        public Nullable<System.DateTime> csTime_h { get; set; }
        public string csStatus { get; set; }
        public string csDesc { get; set; }
        public string csEndFlag { get; set; }
        public Nullable<System.DateTime> csEndTime { get; set; }
        public string csAccept { get; set; }
        public string csContact { get; set; }
        public string csTel { get; set; }
        public string csPlan { get; set; }
        public string uCode { get; set; }
        public Nullable<System.DateTime> csCreateTime { get; set; }
        public string csRptName { get; set; }
        public Nullable<int> csRptSex { get; set; }
        public Nullable<int> csRptAge { get; set; }
        public string csRptWorkUnit { get; set; }
        public string csRptLiveAddr { get; set; }
        public string csRptTel { get; set; }
        public Nullable<System.DateTime> csRptTime { get; set; }
        public string csRecept { get; set; }
        public string csRptType { get; set; }
        public Nullable<System.DateTime> csReceptTime { get; set; }
        public string csHowDiscover { get; set; }
        public Nullable<System.DateTime> csDiscoverTime { get; set; }
        public string csArea { get; set; }
        public string csSceneType { get; set; }
        public string csHurtLevel { get; set; }
        public Nullable<System.DateTime> csRegDate { get; set; }
        public string csRegInst { get; set; }
        public string csFlag { get; set; }
        public string csEmail { get; set; }
        public string csReregReason { get; set; }
        public Nullable<int> csSuspCount { get; set; }
        public Nullable<int> csHurtCount { get; set; }
        public Nullable<int> csDeadCount { get; set; }
        public Nullable<long> csLoseVal { get; set; }
        public string csChoseOpp { get; set; }
        public string csChoseLoc { get; set; }
        public string csChoseObj { get; set; }
        public string csChoseArt { get; set; }
        public string csCrimeTrick { get; set; }
        public string csCrimePat { get; set; }
        public string csCrimeTool { get; set; }
        public string csEndDept { get; set; }
        public string csEndWay { get; set; }
        public string csEndType { get; set; }
        public Nullable<long> csCaptureVal { get; set; }
        public Nullable<short> csCaptCount { get; set; }
        public Nullable<short> csGrpCount { get; set; }
        public string csGrpKind { get; set; }
        public Nullable<short> csGrpInvCount { get; set; }
        public string csEndDesc { get; set; }
        public string csRescueType { get; set; }
        public Nullable<short> csRescueCount { get; set; }
        public Nullable<short> csEndChainCount { get; set; }
        public string ID { get; set; }
        public Nullable<double> csLatitude { get; set; }
        public Nullable<double> csLongitude { get; set; }
        public Nullable<System.DateTime> csUpdateTime { get; set; }
    }
}
