//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCaseGp
    {
        public Nullable<bool> isDel { get; set; }
        public byte[] recSN { get; set; }
        public string csCode { get; set; }
        public string gpsTargetType { get; set; }
        public string devCode { get; set; }
        public string uCode { get; set; }
        public Nullable<decimal> gpsLongitude { get; set; }
        public Nullable<decimal> gpsLatitude { get; set; }
        public Nullable<System.DateTime> gpsTime { get; set; }
        public string ID { get; set; }
        public Nullable<decimal> altitude { get; set; }
        public Nullable<decimal> speed { get; set; }
        public Nullable<decimal> accelerationX { get; set; }
        public Nullable<decimal> accelerationY { get; set; }
        public Nullable<decimal> accelerationZ { get; set; }
    }
}
