//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDepartment
    {
        public Nullable<int> isDel { get; set; }
        public byte[] recSN { get; set; }
        public string dCode { get; set; }
        public string dName { get; set; }
        public string dFather { get; set; }
        public string dDesc { get; set; }
        public long ID { get; set; }
        public Nullable<int> sort_id { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string farther { get; set; }
        public string dAbbr { get; set; }
    }
}
