//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDevice
    {
        public Nullable<bool> isDel { get; set; }
        public byte[] recSN { get; set; }
        public string devCode { get; set; }
        public string devName { get; set; }
        public string devType { get; set; }
        public string devBrand { get; set; }
        public string devModel { get; set; }
        public Nullable<System.DateTime> devPDate { get; set; }
        public Nullable<int> devGPeriod { get; set; }
        public Nullable<System.DateTime> devSTime { get; set; }
        public string uCode { get; set; }
        public string devStatus { get; set; }
        public string devPhoto { get; set; }
        public string devRemark { get; set; }
        public string ID { get; set; }
        public string devSN { get; set; }
    }
}
