//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDiscussionGroup
    {
        public long ID { get; set; }
        public Nullable<int> isDel { get; set; }
        public byte[] recSN { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public string discussionCode { get; set; }
        public string discussionName { get; set; }
        public string createdUserCode { get; set; }
        public string createdUserName { get; set; }
        public string csCode { get; set; }
        public string type { get; set; }
        public string relativegroup { get; set; }
        public string relativegroupid { get; set; }
        public string dept { get; set; }
        public string deptid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    }
}
