//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFileDetail
    {
        public Nullable<bool> isDel { get; set; }
        public byte[] recSN { get; set; }
        public string attRsCode { get; set; }
        public string fCode { get; set; }
        public string fName { get; set; }
        public Nullable<long> fSize { get; set; }
        public string fAbstract { get; set; }
        public string fFirstFrame { get; set; }
        public Nullable<System.DateTime> fStartTime { get; set; }
        public Nullable<System.DateTime> fEndTime { get; set; }
        public string ID { get; set; }
        public string fRelativePath { get; set; }
        public string virtualId { get; set; }
        public string fduration { get; set; }
    }
}
