//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMenu
    {
        public bool isDel { get; set; }
        public byte[] recSN { get; set; }
        public string mnuCode { get; set; }
        public string mnuName { get; set; }
        public string mnuDesc { get; set; }
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PID { get; set; }
        public Nullable<System.Guid> funID { get; set; }
        public string mnuUrl { get; set; }
        public Nullable<int> mnuOrder { get; set; }
    }
}
