//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUnit
    {
        public string ID { get; set; }
        public string unitCode { get; set; }
        public Nullable<int> maxUserNumber { get; set; }
        public Nullable<int> maxVideoUserNumber { get; set; }
        public string unitName { get; set; }
        public string unitLoginName { get; set; }
        public string uHeadPortrait { get; set; }
        public string PIC { get; set; }
        public string Duty { get; set; }
        public string Tel { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string detailAddress { get; set; }
        public string Remarks { get; set; }
    }
}
