//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public long ID { get; set; }
        public Nullable<int> isDel { get; set; }
        public byte[] recSN { get; set; }
        public string uCode { get; set; }
        public string uPassword { get; set; }
        public string uSalt { get; set; }
        public string uBelong { get; set; }
        public Nullable<int> uIsActive { get; set; }
        public string rName { get; set; }
        public string pcNum { get; set; }
        public string uName { get; set; }
        public string uSex { get; set; }
        public string uDuty { get; set; }
        public string dCode { get; set; }
        public string uTel { get; set; }
        public string uShortNum { get; set; }
        public string uHeadPortrait { get; set; }
        public string dName { get; set; }
        public string LYCID { get; set; }
        public Nullable<short> loginFailTimes { get; set; }
        public Nullable<System.DateTime> lastLoginTime { get; set; }
        public string uRemarks { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string uDepartment { get; set; }
        public string accountType { get; set; }
        public string uEmployeenum { get; set; }
        public Nullable<bool> uIshistory { get; set; }
        public Nullable<int> uIsUnilt { get; set; }
        public Nullable<bool> uIsAccontion { get; set; }
        public string uUnitCode { get; set; }
        public long roleid { get; set; }
        public int roleType { get; set; }
        public string groupid { get; set; }
        public string groupName { get; set; }
        public Nullable<int> deviceid { get; set; }
        public string deviceESN { get; set; }
        public string devicetype { get; set; }
        public string status { get; set; }
        public string purpose { get; set; }
    }
}
