//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIMS.LiveVideoSDK.Bll.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserIMData
    {
        public long ID { get; set; }
        public Nullable<bool> isDel { get; set; }
        public byte[] recSN { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public string uCode { get; set; }
        public string csCode { get; set; }
        public string positionName { get; set; }
        public Nullable<decimal> altitude { get; set; }
        public Nullable<decimal> speed { get; set; }
        public Nullable<decimal> accelerationX { get; set; }
        public Nullable<decimal> accelerationY { get; set; }
        public Nullable<decimal> accelerationZ { get; set; }
        public string type { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
    }
}
