//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRGcms.Web.mpdsServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nm.pdt.org.cn", ConfigurationName="mpdsServices.CityUserInterface")]
    public interface CityUserInterface {
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 esnList 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="userESNSync", ReplyAction="*")]
        GRGcms.Web.mpdsServices.userESNSyncResponse userESNSync(GRGcms.Web.mpdsServices.userESNSync request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="setRadioUserRoamAttr", ReplyAction="*")]
        GRGcms.Web.mpdsServices.setRadioUserRoamAttrResponse setRadioUserRoamAttr(GRGcms.Web.mpdsServices.setRadioUserRoamAttr request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="orgInfoQuery", ReplyAction="*")]
        GRGcms.Web.mpdsServices.orgInfoQueryResponse orgInfoQuery(GRGcms.Web.mpdsServices.orgInfoQuery request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="userInfoQuery", ReplyAction="*")]
        GRGcms.Web.mpdsServices.userInfoQueryResponse userInfoQuery(GRGcms.Web.mpdsServices.userInfoQuery request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="termUseInfoQuery", ReplyAction="*")]
        GRGcms.Web.mpdsServices.termUseInfoQueryResponse termUseInfoQuery(GRGcms.Web.mpdsServices.termUseInfoQuery request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="switchStateQuery", ReplyAction="*")]
        GRGcms.Web.mpdsServices.switchStateQueryResponse switchStateQuery(GRGcms.Web.mpdsServices.switchStateQuery request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="setRadioUserRoamToList", ReplyAction="*")]
        GRGcms.Web.mpdsServices.setRadioUserRoamToListResponse setRadioUserRoamToList(GRGcms.Web.mpdsServices.setRadioUserRoamToList request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="delRoamInTalkGroup", ReplyAction="*")]
        GRGcms.Web.mpdsServices.delRoamInTalkGroupResponse delRoamInTalkGroup(GRGcms.Web.mpdsServices.delRoamInTalkGroup request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="setRadioUserRoamToTscList", ReplyAction="*")]
        GRGcms.Web.mpdsServices.setRadioUserRoamToTscListResponse setRadioUserRoamToTscList(GRGcms.Web.mpdsServices.setRadioUserRoamToTscList request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="groupInfoQuery", ReplyAction="*")]
        GRGcms.Web.mpdsServices.groupInfoQueryResponse groupInfoQuery(GRGcms.Web.mpdsServices.groupInfoQuery request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="termDevInfoQuery", ReplyAction="*")]
        GRGcms.Web.mpdsServices.termDevInfoQueryResponse termDevInfoQuery(GRGcms.Web.mpdsServices.termDevInfoQuery request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="isAlive", ReplyAction="*")]
        GRGcms.Web.mpdsServices.isAliveResponse isAlive(GRGcms.Web.mpdsServices.isAlive request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="delRoamInRadioUser", ReplyAction="*")]
        GRGcms.Web.mpdsServices.delRoamInRadioUserResponse delRoamInRadioUser(GRGcms.Web.mpdsServices.delRoamInRadioUser request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="roamUserQuery", ReplyAction="*")]
        GRGcms.Web.mpdsServices.roamUserQueryResponse roamUserQuery(GRGcms.Web.mpdsServices.roamUserQuery request);
        
        // CODEGEN: 命名空间 http://nm.pdt.org.cn 的元素名称 input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="roamToQuery", ReplyAction="*")]
        GRGcms.Web.mpdsServices.roamToQueryResponse roamToQuery(GRGcms.Web.mpdsServices.roamToQuery request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userESNSync {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userESNSync", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.userESNSyncBody Body;
        
        public userESNSync() {
        }
        
        public userESNSync(GRGcms.Web.mpdsServices.userESNSyncBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class userESNSyncBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string esnList;
        
        public userESNSyncBody() {
        }
        
        public userESNSyncBody(string esnList) {
            this.esnList = esnList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userESNSyncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userESNSyncResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.userESNSyncResponseBody Body;
        
        public userESNSyncResponse() {
        }
        
        public userESNSyncResponse(GRGcms.Web.mpdsServices.userESNSyncResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class userESNSyncResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultIsOK;
        
        public userESNSyncResponseBody() {
        }
        
        public userESNSyncResponseBody(string resultIsOK) {
            this.resultIsOK = resultIsOK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setRadioUserRoamAttr {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setRadioUserRoamAttr", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.setRadioUserRoamAttrBody Body;
        
        public setRadioUserRoamAttr() {
        }
        
        public setRadioUserRoamAttr(GRGcms.Web.mpdsServices.setRadioUserRoamAttrBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class setRadioUserRoamAttrBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public setRadioUserRoamAttrBody() {
        }
        
        public setRadioUserRoamAttrBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setRadioUserRoamAttrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setRadioUserRoamAttrResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.setRadioUserRoamAttrResponseBody Body;
        
        public setRadioUserRoamAttrResponse() {
        }
        
        public setRadioUserRoamAttrResponse(GRGcms.Web.mpdsServices.setRadioUserRoamAttrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class setRadioUserRoamAttrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultIsOK;
        
        public setRadioUserRoamAttrResponseBody() {
        }
        
        public setRadioUserRoamAttrResponseBody(string resultIsOK) {
            this.resultIsOK = resultIsOK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orgInfoQuery {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orgInfoQuery", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.orgInfoQueryBody Body;
        
        public orgInfoQuery() {
        }
        
        public orgInfoQuery(GRGcms.Web.mpdsServices.orgInfoQueryBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class orgInfoQueryBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public orgInfoQueryBody() {
        }
        
        public orgInfoQueryBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class orgInfoQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orgInfoQueryResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.orgInfoQueryResponseBody Body;
        
        public orgInfoQueryResponse() {
        }
        
        public orgInfoQueryResponse(GRGcms.Web.mpdsServices.orgInfoQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class orgInfoQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string orgList;
        
        public orgInfoQueryResponseBody() {
        }
        
        public orgInfoQueryResponseBody(string orgList) {
            this.orgList = orgList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userInfoQuery {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userInfoQuery", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.userInfoQueryBody Body;
        
        public userInfoQuery() {
        }
        
        public userInfoQuery(GRGcms.Web.mpdsServices.userInfoQueryBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class userInfoQueryBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public userInfoQueryBody() {
        }
        
        public userInfoQueryBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userInfoQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userInfoQueryResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.userInfoQueryResponseBody Body;
        
        public userInfoQueryResponse() {
        }
        
        public userInfoQueryResponse(GRGcms.Web.mpdsServices.userInfoQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class userInfoQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userList;
        
        public userInfoQueryResponseBody() {
        }
        
        public userInfoQueryResponseBody(string userList) {
            this.userList = userList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class termUseInfoQuery {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="termUseInfoQuery", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.termUseInfoQueryBody Body;
        
        public termUseInfoQuery() {
        }
        
        public termUseInfoQuery(GRGcms.Web.mpdsServices.termUseInfoQueryBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class termUseInfoQueryBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public termUseInfoQueryBody() {
        }
        
        public termUseInfoQueryBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class termUseInfoQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="termUseInfoQueryResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.termUseInfoQueryResponseBody Body;
        
        public termUseInfoQueryResponse() {
        }
        
        public termUseInfoQueryResponse(GRGcms.Web.mpdsServices.termUseInfoQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class termUseInfoQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string devList;
        
        public termUseInfoQueryResponseBody() {
        }
        
        public termUseInfoQueryResponseBody(string devList) {
            this.devList = devList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class switchStateQuery {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="switchStateQuery", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.switchStateQueryBody Body;
        
        public switchStateQuery() {
        }
        
        public switchStateQuery(GRGcms.Web.mpdsServices.switchStateQueryBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class switchStateQueryBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public switchStateQueryBody() {
        }
        
        public switchStateQueryBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class switchStateQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="switchStateQueryResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.switchStateQueryResponseBody Body;
        
        public switchStateQueryResponse() {
        }
        
        public switchStateQueryResponse(GRGcms.Web.mpdsServices.switchStateQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class switchStateQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string onOffList;
        
        public switchStateQueryResponseBody() {
        }
        
        public switchStateQueryResponseBody(string onOffList) {
            this.onOffList = onOffList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setRadioUserRoamToList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setRadioUserRoamToList", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.setRadioUserRoamToListBody Body;
        
        public setRadioUserRoamToList() {
        }
        
        public setRadioUserRoamToList(GRGcms.Web.mpdsServices.setRadioUserRoamToListBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class setRadioUserRoamToListBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public setRadioUserRoamToListBody() {
        }
        
        public setRadioUserRoamToListBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setRadioUserRoamToListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setRadioUserRoamToListResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.setRadioUserRoamToListResponseBody Body;
        
        public setRadioUserRoamToListResponse() {
        }
        
        public setRadioUserRoamToListResponse(GRGcms.Web.mpdsServices.setRadioUserRoamToListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class setRadioUserRoamToListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultIsOK;
        
        public setRadioUserRoamToListResponseBody() {
        }
        
        public setRadioUserRoamToListResponseBody(string resultIsOK) {
            this.resultIsOK = resultIsOK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delRoamInTalkGroup {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delRoamInTalkGroup", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.delRoamInTalkGroupBody Body;
        
        public delRoamInTalkGroup() {
        }
        
        public delRoamInTalkGroup(GRGcms.Web.mpdsServices.delRoamInTalkGroupBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class delRoamInTalkGroupBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public delRoamInTalkGroupBody() {
        }
        
        public delRoamInTalkGroupBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delRoamInTalkGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delRoamInTalkGroupResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.delRoamInTalkGroupResponseBody Body;
        
        public delRoamInTalkGroupResponse() {
        }
        
        public delRoamInTalkGroupResponse(GRGcms.Web.mpdsServices.delRoamInTalkGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class delRoamInTalkGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultIsOK;
        
        public delRoamInTalkGroupResponseBody() {
        }
        
        public delRoamInTalkGroupResponseBody(string resultIsOK) {
            this.resultIsOK = resultIsOK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setRadioUserRoamToTscList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setRadioUserRoamToTscList", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.setRadioUserRoamToTscListBody Body;
        
        public setRadioUserRoamToTscList() {
        }
        
        public setRadioUserRoamToTscList(GRGcms.Web.mpdsServices.setRadioUserRoamToTscListBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class setRadioUserRoamToTscListBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public setRadioUserRoamToTscListBody() {
        }
        
        public setRadioUserRoamToTscListBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setRadioUserRoamToTscListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setRadioUserRoamToTscListResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.setRadioUserRoamToTscListResponseBody Body;
        
        public setRadioUserRoamToTscListResponse() {
        }
        
        public setRadioUserRoamToTscListResponse(GRGcms.Web.mpdsServices.setRadioUserRoamToTscListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class setRadioUserRoamToTscListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultIsOK;
        
        public setRadioUserRoamToTscListResponseBody() {
        }
        
        public setRadioUserRoamToTscListResponseBody(string resultIsOK) {
            this.resultIsOK = resultIsOK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class groupInfoQuery {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="groupInfoQuery", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.groupInfoQueryBody Body;
        
        public groupInfoQuery() {
        }
        
        public groupInfoQuery(GRGcms.Web.mpdsServices.groupInfoQueryBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class groupInfoQueryBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public groupInfoQueryBody() {
        }
        
        public groupInfoQueryBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class groupInfoQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="groupInfoQueryResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.groupInfoQueryResponseBody Body;
        
        public groupInfoQueryResponse() {
        }
        
        public groupInfoQueryResponse(GRGcms.Web.mpdsServices.groupInfoQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class groupInfoQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupList;
        
        public groupInfoQueryResponseBody() {
        }
        
        public groupInfoQueryResponseBody(string groupList) {
            this.groupList = groupList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class termDevInfoQuery {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="termDevInfoQuery", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.termDevInfoQueryBody Body;
        
        public termDevInfoQuery() {
        }
        
        public termDevInfoQuery(GRGcms.Web.mpdsServices.termDevInfoQueryBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class termDevInfoQueryBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public termDevInfoQueryBody() {
        }
        
        public termDevInfoQueryBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class termDevInfoQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="termDevInfoQueryResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.termDevInfoQueryResponseBody Body;
        
        public termDevInfoQueryResponse() {
        }
        
        public termDevInfoQueryResponse(GRGcms.Web.mpdsServices.termDevInfoQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class termDevInfoQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string devList;
        
        public termDevInfoQueryResponseBody() {
        }
        
        public termDevInfoQueryResponseBody(string devList) {
            this.devList = devList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isAlive {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isAlive", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.isAliveBody Body;
        
        public isAlive() {
        }
        
        public isAlive(GRGcms.Web.mpdsServices.isAliveBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class isAliveBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public isAliveBody() {
        }
        
        public isAliveBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isAliveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isAliveResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.isAliveResponseBody Body;
        
        public isAliveResponse() {
        }
        
        public isAliveResponse(GRGcms.Web.mpdsServices.isAliveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class isAliveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultIsAlive;
        
        public isAliveResponseBody() {
        }
        
        public isAliveResponseBody(string resultIsAlive) {
            this.resultIsAlive = resultIsAlive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delRoamInRadioUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delRoamInRadioUser", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.delRoamInRadioUserBody Body;
        
        public delRoamInRadioUser() {
        }
        
        public delRoamInRadioUser(GRGcms.Web.mpdsServices.delRoamInRadioUserBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class delRoamInRadioUserBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public delRoamInRadioUserBody() {
        }
        
        public delRoamInRadioUserBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delRoamInRadioUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delRoamInRadioUserResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.delRoamInRadioUserResponseBody Body;
        
        public delRoamInRadioUserResponse() {
        }
        
        public delRoamInRadioUserResponse(GRGcms.Web.mpdsServices.delRoamInRadioUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class delRoamInRadioUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultIsOK;
        
        public delRoamInRadioUserResponseBody() {
        }
        
        public delRoamInRadioUserResponseBody(string resultIsOK) {
            this.resultIsOK = resultIsOK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class roamUserQuery {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="roamUserQuery", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.roamUserQueryBody Body;
        
        public roamUserQuery() {
        }
        
        public roamUserQuery(GRGcms.Web.mpdsServices.roamUserQueryBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class roamUserQueryBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public roamUserQueryBody() {
        }
        
        public roamUserQueryBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class roamUserQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="roamUserQueryResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.roamUserQueryResponseBody Body;
        
        public roamUserQueryResponse() {
        }
        
        public roamUserQueryResponse(GRGcms.Web.mpdsServices.roamUserQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class roamUserQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string roamUserList;
        
        public roamUserQueryResponseBody() {
        }
        
        public roamUserQueryResponseBody(string roamUserList) {
            this.roamUserList = roamUserList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class roamToQuery {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="roamToQuery", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.roamToQueryBody Body;
        
        public roamToQuery() {
        }
        
        public roamToQuery(GRGcms.Web.mpdsServices.roamToQueryBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class roamToQueryBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public roamToQueryBody() {
        }
        
        public roamToQueryBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class roamToQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="roamToQueryResponse", Namespace="http://nm.pdt.org.cn", Order=0)]
        public GRGcms.Web.mpdsServices.roamToQueryResponseBody Body;
        
        public roamToQueryResponse() {
        }
        
        public roamToQueryResponse(GRGcms.Web.mpdsServices.roamToQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nm.pdt.org.cn")]
    public partial class roamToQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string regionList;
        
        public roamToQueryResponseBody() {
        }
        
        public roamToQueryResponseBody(string regionList) {
            this.regionList = regionList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CityUserInterfaceChannel : GRGcms.Web.mpdsServices.CityUserInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CityUserInterfaceClient : System.ServiceModel.ClientBase<GRGcms.Web.mpdsServices.CityUserInterface>, GRGcms.Web.mpdsServices.CityUserInterface {
        
        public CityUserInterfaceClient() {
        }
        
        public CityUserInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CityUserInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CityUserInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CityUserInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.userESNSyncResponse GRGcms.Web.mpdsServices.CityUserInterface.userESNSync(GRGcms.Web.mpdsServices.userESNSync request) {
            return base.Channel.userESNSync(request);
        }
        
        public string userESNSync(string esnList) {
            GRGcms.Web.mpdsServices.userESNSync inValue = new GRGcms.Web.mpdsServices.userESNSync();
            inValue.Body = new GRGcms.Web.mpdsServices.userESNSyncBody();
            inValue.Body.esnList = esnList;
            GRGcms.Web.mpdsServices.userESNSyncResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).userESNSync(inValue);
            return retVal.Body.resultIsOK;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.setRadioUserRoamAttrResponse GRGcms.Web.mpdsServices.CityUserInterface.setRadioUserRoamAttr(GRGcms.Web.mpdsServices.setRadioUserRoamAttr request) {
            return base.Channel.setRadioUserRoamAttr(request);
        }
        
        public string setRadioUserRoamAttr(string input) {
            GRGcms.Web.mpdsServices.setRadioUserRoamAttr inValue = new GRGcms.Web.mpdsServices.setRadioUserRoamAttr();
            inValue.Body = new GRGcms.Web.mpdsServices.setRadioUserRoamAttrBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.setRadioUserRoamAttrResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).setRadioUserRoamAttr(inValue);
            return retVal.Body.resultIsOK;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.orgInfoQueryResponse GRGcms.Web.mpdsServices.CityUserInterface.orgInfoQuery(GRGcms.Web.mpdsServices.orgInfoQuery request) {
            return base.Channel.orgInfoQuery(request);
        }
        
        public string orgInfoQuery(string input) {
            GRGcms.Web.mpdsServices.orgInfoQuery inValue = new GRGcms.Web.mpdsServices.orgInfoQuery();
            inValue.Body = new GRGcms.Web.mpdsServices.orgInfoQueryBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.orgInfoQueryResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).orgInfoQuery(inValue);
            return retVal.Body.orgList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.userInfoQueryResponse GRGcms.Web.mpdsServices.CityUserInterface.userInfoQuery(GRGcms.Web.mpdsServices.userInfoQuery request) {
            return base.Channel.userInfoQuery(request);
        }
        
        public string userInfoQuery(string input) {
            GRGcms.Web.mpdsServices.userInfoQuery inValue = new GRGcms.Web.mpdsServices.userInfoQuery();
            inValue.Body = new GRGcms.Web.mpdsServices.userInfoQueryBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.userInfoQueryResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).userInfoQuery(inValue);
            return retVal.Body.userList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.termUseInfoQueryResponse GRGcms.Web.mpdsServices.CityUserInterface.termUseInfoQuery(GRGcms.Web.mpdsServices.termUseInfoQuery request) {
            return base.Channel.termUseInfoQuery(request);
        }
        
        public string termUseInfoQuery(string input) {
            GRGcms.Web.mpdsServices.termUseInfoQuery inValue = new GRGcms.Web.mpdsServices.termUseInfoQuery();
            inValue.Body = new GRGcms.Web.mpdsServices.termUseInfoQueryBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.termUseInfoQueryResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).termUseInfoQuery(inValue);
            return retVal.Body.devList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.switchStateQueryResponse GRGcms.Web.mpdsServices.CityUserInterface.switchStateQuery(GRGcms.Web.mpdsServices.switchStateQuery request) {
            return base.Channel.switchStateQuery(request);
        }
        
        public string switchStateQuery(string input) {
            GRGcms.Web.mpdsServices.switchStateQuery inValue = new GRGcms.Web.mpdsServices.switchStateQuery();
            inValue.Body = new GRGcms.Web.mpdsServices.switchStateQueryBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.switchStateQueryResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).switchStateQuery(inValue);
            return retVal.Body.onOffList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.setRadioUserRoamToListResponse GRGcms.Web.mpdsServices.CityUserInterface.setRadioUserRoamToList(GRGcms.Web.mpdsServices.setRadioUserRoamToList request) {
            return base.Channel.setRadioUserRoamToList(request);
        }
        
        public string setRadioUserRoamToList(string input) {
            GRGcms.Web.mpdsServices.setRadioUserRoamToList inValue = new GRGcms.Web.mpdsServices.setRadioUserRoamToList();
            inValue.Body = new GRGcms.Web.mpdsServices.setRadioUserRoamToListBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.setRadioUserRoamToListResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).setRadioUserRoamToList(inValue);
            return retVal.Body.resultIsOK;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.delRoamInTalkGroupResponse GRGcms.Web.mpdsServices.CityUserInterface.delRoamInTalkGroup(GRGcms.Web.mpdsServices.delRoamInTalkGroup request) {
            return base.Channel.delRoamInTalkGroup(request);
        }
        
        public string delRoamInTalkGroup(string input) {
            GRGcms.Web.mpdsServices.delRoamInTalkGroup inValue = new GRGcms.Web.mpdsServices.delRoamInTalkGroup();
            inValue.Body = new GRGcms.Web.mpdsServices.delRoamInTalkGroupBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.delRoamInTalkGroupResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).delRoamInTalkGroup(inValue);
            return retVal.Body.resultIsOK;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.setRadioUserRoamToTscListResponse GRGcms.Web.mpdsServices.CityUserInterface.setRadioUserRoamToTscList(GRGcms.Web.mpdsServices.setRadioUserRoamToTscList request) {
            return base.Channel.setRadioUserRoamToTscList(request);
        }
        
        public string setRadioUserRoamToTscList(string input) {
            GRGcms.Web.mpdsServices.setRadioUserRoamToTscList inValue = new GRGcms.Web.mpdsServices.setRadioUserRoamToTscList();
            inValue.Body = new GRGcms.Web.mpdsServices.setRadioUserRoamToTscListBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.setRadioUserRoamToTscListResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).setRadioUserRoamToTscList(inValue);
            return retVal.Body.resultIsOK;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.groupInfoQueryResponse GRGcms.Web.mpdsServices.CityUserInterface.groupInfoQuery(GRGcms.Web.mpdsServices.groupInfoQuery request) {
            return base.Channel.groupInfoQuery(request);
        }
        
        public string groupInfoQuery(string input) {
            GRGcms.Web.mpdsServices.groupInfoQuery inValue = new GRGcms.Web.mpdsServices.groupInfoQuery();
            inValue.Body = new GRGcms.Web.mpdsServices.groupInfoQueryBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.groupInfoQueryResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).groupInfoQuery(inValue);
            return retVal.Body.groupList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.termDevInfoQueryResponse GRGcms.Web.mpdsServices.CityUserInterface.termDevInfoQuery(GRGcms.Web.mpdsServices.termDevInfoQuery request) {
            return base.Channel.termDevInfoQuery(request);
        }
        
        public string termDevInfoQuery(string input) {
            GRGcms.Web.mpdsServices.termDevInfoQuery inValue = new GRGcms.Web.mpdsServices.termDevInfoQuery();
            inValue.Body = new GRGcms.Web.mpdsServices.termDevInfoQueryBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.termDevInfoQueryResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).termDevInfoQuery(inValue);
            return retVal.Body.devList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.isAliveResponse GRGcms.Web.mpdsServices.CityUserInterface.isAlive(GRGcms.Web.mpdsServices.isAlive request) {
            return base.Channel.isAlive(request);
        }
        
        public string isAlive(string input) {
            GRGcms.Web.mpdsServices.isAlive inValue = new GRGcms.Web.mpdsServices.isAlive();
            inValue.Body = new GRGcms.Web.mpdsServices.isAliveBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.isAliveResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).isAlive(inValue);
            return retVal.Body.resultIsAlive;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.delRoamInRadioUserResponse GRGcms.Web.mpdsServices.CityUserInterface.delRoamInRadioUser(GRGcms.Web.mpdsServices.delRoamInRadioUser request) {
            return base.Channel.delRoamInRadioUser(request);
        }
        
        public string delRoamInRadioUser(string input) {
            GRGcms.Web.mpdsServices.delRoamInRadioUser inValue = new GRGcms.Web.mpdsServices.delRoamInRadioUser();
            inValue.Body = new GRGcms.Web.mpdsServices.delRoamInRadioUserBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.delRoamInRadioUserResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).delRoamInRadioUser(inValue);
            return retVal.Body.resultIsOK;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.roamUserQueryResponse GRGcms.Web.mpdsServices.CityUserInterface.roamUserQuery(GRGcms.Web.mpdsServices.roamUserQuery request) {
            return base.Channel.roamUserQuery(request);
        }
        
        public string roamUserQuery(string input) {
            GRGcms.Web.mpdsServices.roamUserQuery inValue = new GRGcms.Web.mpdsServices.roamUserQuery();
            inValue.Body = new GRGcms.Web.mpdsServices.roamUserQueryBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.roamUserQueryResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).roamUserQuery(inValue);
            return retVal.Body.roamUserList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRGcms.Web.mpdsServices.roamToQueryResponse GRGcms.Web.mpdsServices.CityUserInterface.roamToQuery(GRGcms.Web.mpdsServices.roamToQuery request) {
            return base.Channel.roamToQuery(request);
        }
        
        public string roamToQuery(string input) {
            GRGcms.Web.mpdsServices.roamToQuery inValue = new GRGcms.Web.mpdsServices.roamToQuery();
            inValue.Body = new GRGcms.Web.mpdsServices.roamToQueryBody();
            inValue.Body.input = input;
            GRGcms.Web.mpdsServices.roamToQueryResponse retVal = ((GRGcms.Web.mpdsServices.CityUserInterface)(this)).roamToQuery(inValue);
            return retVal.Body.regionList;
        }
    }
}
